spring:
  datasource:
    url: jdbc:postgresql://pgm-bp1j0w334bo5qm88go.rwlb.rds.aliyuncs.com:5432/jblmj_ai_agent
    username: jblmj
    password: Jblmj=12345
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000

# 修改日志级别，查看更多调试信息
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.jdbc: DEBUG
